baseURL = '/'

title = "Omai"

[params]
  description = "Omai's hemsida"
  author = "Omai"
  turnstileSiteKey = "0x4AAAAAACNQSMXZq9WoK5m_"

disableKinds = ['taxonomy', 'term', 'taxonomyTerm']

[permalinks]
  om-ai = '/om-ai/:slug/'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']

# Minification settings
[minify]
  disableHTML = false
  disableCSS = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
