name: Hugo Static Site Deployment

on:
  push:
    branches:
      - main # √Ñndra detta till namnet p√• din huvudbranch om den heter n√•got annat (t.ex. 'master')
  
  # Till√•ter att du k√∂r workflow manuellt fr√•n GitHub-gr√§nssnittet
  workflow_dispatch:

# St√§ll in n√∂dv√§ndiga beh√∂righeter f√∂r deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      BUCKET_NAME: omai-www 
      GCP_PROJECT_NO: 590926833494 
      GCP_PROJECT_ID: linen-compiler-479716-j7
      WIF_POOL_ID: github-deploy-pool
      WIF_PROVIDER_ID: github-oidc-provider # <-- Nytt Provider ID
      WIF_SERVICE_ACCOUNT: github-hugo-deployer@linen-compiler-479716-j7.iam.gserviceaccount.com 
    
    permissions:
      contents: 'read'
      id-token: 'write' 

    steps:
      - name: ‚¨áÔ∏è Checkout kod
        uses: actions/checkout@v4
        with:
          submodules: true # F√∂r att hantera teman som submoduler
          fetch-depth: 0    # F√∂r att Hugo ska kunna h√§mta commit-datum/tid

      - name: üõ†Ô∏è St√§ll in Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          # Du kan l√§gga till extended: true om du anv√§nder SASS/SCSS

      - name: ‚öôÔ∏è Bygg Hugo-sajten
        run: hugo --minify

      # Step 3: Deploy to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: omai-www
          directory: ./public # Path to your built static site (adjust as needed)

